<div class="box-login">
	<h3><?php echo $this->translate( 'sign in to your account' ) ?></h3>
	<p><?php echo $this->translate( 'enter your name and password' ) ?></p>
	<form class="form-login" method="post" action="<?php echo $this->url() ?>">
		<div class="errorHandler alert alert-danger no-display">
			<i class="fa fa-remove-sign"></i>
			<?php echo $this->translate( 'you have some form errors' ) ?>
		</div>
		<fieldset>
			<div class="form-group<?php if ( $this->nickname === false ) : echo ' has-error'; endif; ?>">
				<span class="input-icon">
					<input type="text" name="nickname" class="form-control"
					 placeholder="<?php echo $this->translate( 'nickname' ) ?>"
					>
					<i class="fa fa-user"></i>
					<?php if ( $this->nickname === false ) : ?>
						<span class="help-block">
							<?php echo $this->translate( 'user does not exists' ) ?>
						</span>
					<?php endif ?>
				</span>
			</div>
			<div class="form-group form-actions<?php if ( $this->password === false ) : echo ' has-error'; endif; ?>">
				<span class="input-icon">
					<input type="password" name="password" class="form-control password"
					 placeholder="<?php echo $this->translate( 'password' ) ?>"
					>
					<i class="fa fa-lock"></i>
					<?php if ( $this->password === false ) : ?>
						<span class="help-block">
							<?php echo $this->translate( 'wrong password' ) ?>
						</span>
					<?php endif ?>
				</span>
			</div>
			<div class="form-actions">
				<button type="submit" class="btn btn-bricky pull-right">
					<?php echo $this->translate( 'login' ) ?>
					<i class="fa fa-arrow-circle-right"></i>
				</button>
			</div>
		</fieldset>
	</form>
</div>