<div class="ecwid">
	<h1><?php echo $this->translate( 'Displaying membership and discount card in customer shop account' ) ?></h1>
	<div class="page">
		<div class="container">
			<p>For displaying membership and discount card in customer shop account please follow the instructions below:</p>
			<p>&nbsp;</p>
			<p>1)	Copy code from <i>Update theme templates</i>&nbsp; window.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/code/updatethemeteplate_1.png' ) ?>" /></p>
			<p>2)	Open <i>Template</i>&nbsp; section.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/code/template_2.png' ) ?>" /></p>
			<p>3)	Click on the <i>Edit HTML</i>&nbsp; link at <i>Templates</i>&nbsp; page.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/code/edithtmllink_3.png' ) ?>" /></p>
			<p>4)	Insert copied code before &lt;/head&gt; or &lt;/body&gt; tags.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/code/fileeditor_4.png' ) ?>" /></p>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->