<div class="ecwid">
	<h1><?php echo $this->translate( 'Getting the Order API secret key' ) ?></h1>
	<div class="page">
		<div class="container">
			<p>You can find the Order API secret key as follows:</p>
			<p>&nbsp;</p>
			<p>1)   Open your account in Ecwid.</p>
			<p>&nbsp;</p>
			<p>2)	Go to <i>System Settings</i>&nbsp; tab.</p>
			<p>&nbsp;</p>
			<p>3)	Click on <i>API</i>&nbsp; link to open the <i>API Settings</i>&nbsp; page.</p>
			<p>&nbsp;</p>
			<p>4)	Copy the <i>Order API secret key</i>&nbsp; from the <i>Order API</i>&nbsp; section.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/password1/Ecwid-Settings-API-orders.png' ) ?>" /></p>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->