<div class="magento">
	<h1><?php echo $this->translate( 'Can I find the Store View Code' ) ?></h1>
	<div class="page">
		<div class="container">
			<p>You can find the Store View Code in your Magento Admin Panel by going to <b>System > Manage Stores</b>.</p>
			<p>Then click the link under the <b>Store View Name</b> column.</p>
			<br />
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/magento/m_7.png' ) ?>" /></p>
			<p>The <b>Store View Code</b> can be found in the Code field.</p>
			<br />
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/magento/m_8.png' ) ?>" /></p>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->