<div class="magento">
	<h1><?php echo $this->translate( 'terms of use' ) ?></h1>
	<div class="page">
		<div class="container">
			<div style="text-align:justify;">
			<p>
			These terms and conditions pertain to SpurIT application (further in the text called Application) including its content and all services. Prior to using this Application, please, read and accept these Terms and Conditions.
			</p>
			<p>
			The Application is owned and administered by the Private Unitary Service Enterprise SpurIT. The fact that you are using any part of this Application, means that you accept the terms and conditions stated below (hereafter collectively referred to as the Agreement). If you do not agree to all these terms and conditions you should not access the Application or use any of its services.
			</p>
			<p>
			<b>Software Usage</b><br />
			Under the terms and conditions of this Agreement, the SpurIT grants you an access to use the Application only for purposes of operating an electronic-commerce store on the Internet.
			</p>
			<p>
			<b>Information Collection and Usage</b><br />
			We collect our Customer’s personal information - the Customer’s username, e-mail (only at the Customer’s consent) and some additional optional information - and use it exclusively for a restricted number of purposes, such as issuing an invoice or keeping in touch with the Customer. Any technical information, such as the Customer’s IP address or browser version, are used only in the aims of our Application technical performance improvement. Any additional information which can be obtained by the Application via API interface provided by a client or third party or obtained from open sources of information is used for performing direct functions described and executed in the Application. Any part of the Customer’s personal information is never revealed to anyone else. We never collect any secure payment information such as the Customer’s credit card data, including CVV/CVV2. This information is only collected through authorized payment gateways such as 2Checkout on their websites.
			</p>
			<p>
			<b>Keeping Information</b><br />
			All collected Information is kept securely. Access to this information may only be provided for authorized employees who have signed a non-disclosure agreement with SpurIT.
			</p>
			<p>
			<a name="refund-policy" id="refund-policy"></a>
			<b>Refund Policy</b><br />
			Since the Application is provided as a service with a trial period (or for free), the refund is not provided after the payment for receiving access to the Application functions. If you had paid for a certain period of using the Application but decided to renounce the use of the Application until the payment expiration date, the refund is not provided. The refund is provided when, for some reasons, SpurIT has to decline the access to the Application for its clients. In this case, the refund is provided in the amount equal to the monthly cost of your current tariff plan. If you had paid for the use of the Application for more than one month, this amount of money will be refunded also.
			</p>
			<p>
			<b>Payment</b><br />
			The Application does not handle payments for its use directly, but it rather forwards these payments to a secure third-party payment gateway which handles all the payment procedures. Any payment issues or disputes should be resolved directly with the payment gateway. Once we have been notified by the payment gateway that a payment was made, and that it has successfully passed a fraud review, access to the product or service being purchased will be granted as soon as possible, however, we make no guarantees of timeliness or immediacy. If the Application tariff plan was changed after the latest payment for the use of the Application, the remaining period of the use of the Application will be multiplied by the proportion of the monthly cost of the previous tariff plan to the monthly cost of the current tariff plan.
			</p>
			<p>
			<b>Changes</b><br />
			SpurtIT reserves the right to make changes to the terms of this Agreement. It is the Customer’s responsibility to periodically check this Agreement for any updates. The Customer understands and agrees that if the Customer uses the Application after the date on which the Agreement was changed, the fact of such usage will be regarded as acceptance of the changes made.
			</p>
			<p>
			<b>Disclaimer of Warranties</b><br />
			The Application is provided "as is". SpurIT hereby disclaims all warranties of any kind, expressed or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. SpurIT does not make any warranty for the Application to be error-free or that access thereto will be continuous or uninterrupted. SpurIT will not be responsible for any data loss, down-time occurring in the process of installation or upgrading of its software products.
			</p>
			<p>
			<b>Limitation of Liability</b><br />
			In no event will SpurIT be liable for any responsibility with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any direct, indirect, deliberate, incidental or consequential damage; (ii) the cost of procurement or substitute products or services; (iii) interruption of use or loss or corruption of data; (iv) any loss of profit (whether incurred directly or indirectly), any loss of business reputation; or (iv) any amount that exceeds the fee paid by the Customer to SpurIT under this agreement. SputIT shall have no liability for any failure or delay due to matters beyond our reasonable control. The limitations on SpurIT's liability above shall apply whether or not SpurIT has been advised of or should have been aware of the possibility of any such losses arising.
			</p>
			<p>
			<b>Indemnification</b><br />
			The Customer agrees to cause no harm to and indemnify SpurIT, and its directors, officers, employees, advertisers or partners any claims, losses, damages (actual and consequential) and expenses, including attorneys' fees and litigation costs, arising from the Customer’s use of the Application, including but not limited to the Customer’s violation of this Agreement.
			</p>
			</div>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->