<div class="opencart">
	<h1><?php echo $this->translate( 'Can I find the Api Token' ) ?></h1>
	<div class="page">
		<div class="container">
			<p>1) First of all you need to <a style="color:#ff6600" href="#">download</a> the Open Cart extension "Unlimited Upsell" and then you need to install it in your Store. How you can install 3rd party modules go <a style="color:#ff6600" href="http://docs.opencart.com/display/opencart/Installing+3rd+party+modules#Installing3rdpartymodules-Installing3rdpartymodules" target="_blank">here</a>.</p>
			<br />
			<p>2) After previous step you can find the <b>Api Token</b> in your Open Cart Admin Panel by going to <b>Extensions > Modules</b> and click on the <b>Edit</b> link opposite the "Unlimited Upsell" extension.</p>
			<br />
			<p><img width="760px" src="<?php echo $this->baseUrl( 'public/images/screenshots/opencart/1.png' ) ?>" /></p>
			<br />
			<p><img width="760px" src="<?php echo $this->baseUrl( 'public/images/screenshots/opencart/2.png' ) ?>" /></p>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->