<div class="prestashop">
	<h1><?php echo $this->translate( 'Can I find the Shop Name' ) ?></h1>
	<div class="page">
		<div class="container">
			<p>1) You can find the Shop Name in your PrestaShop Admin Panel by going to <b>Advanced Parameters > Multistore</b>.</p>
			<br />
			<p>2) Then select the Shop in the block <b>Multistore tree</b></p>
			<br />
			<p>3) The <b>Shop Name</b> can be found under the <b>Shop Name</b> column.</p>
			<br />
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/prestashop/p1.png' ) ?>" /></p>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->