<div class="volusion">
	<h1><?php echo $this->translate( 'Getting the Encrypted password' ) ?></h1>
	<div class="page">
		<div class="container">
			<p>You can find the Encrypted password by following steps:</p>
			<p>&nbsp;</p>
			<p>1)	Go to <i>Inventory</i> &gt; <i>Import/Export</i>.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/password/importexport_1.jpg' ) ?>" /></p>
			<p>2)	Click on <i>Volusion API</i>&nbsp; button at the <i>Import/Export Data</i>&nbsp; page.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/password/volusionapi_2.jpg' ) ?>" /></p>
			<p>3)	Click on <i>Run</i>&nbsp; button for <i>Generic Orders</i>&nbsp; at the <i>Volusion API</i>&nbsp; page.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/password/genericrun_3.jpg' ) ?>" /></p>
			<p>4)	Click on <i>Run</i>&nbsp; button at the <i>Volusion API / Run Generic Orders</i>&nbsp; page.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/password/rungenericorders_4.jpg' ) ?>" /></p>
			<p>5)	Copy the <i>Encrypted Password</i>&nbsp; value from URL at the <i>Volusion API / Run Generic Orders</i>&nbsp; page. The value is separated by "=" and "&amp;" characters.</p>
			<p><img src="<?php echo $this->baseUrl( 'public/images/screenshots/password/encryptedpassword_5.jpg' ) ?>" /></p>
		</div>
	</div>
</div>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->css ?>

/*]]>*/
</style>
<!--[if gte IE 7]>
<style type="text/css">
/*<![CDATA[*/

	<?php echo $this->iecss ?>

/*]]>*/
</style>
<![endif]-->