<div class="error">
	<h1>The strange misunderstanding occurred.</h1>
	<p><?php echo $this->message ?></p>
	<?php if ( isset ( $this->exception ) ) : ?>
		<h2>Exception information:</h2>
		<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
		<h2>Stack trace:</h2>
		<pre><?php echo $this->exception->getTraceAsString() ?></pre>
		<h2>Request Parameters:</h2>
		<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
	<?php endif ?>
</div>