<!DOCTYPE html>
<!--[if IE 8]><html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
	<!--<![endif]-->
	<head>
		<base href="<?php echo $this->serverUrl( $this->baseUrl( '/' ) ) ?>">

		<meta charset="utf-8">
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta name="description" content="">
		<meta name="author" content="">

		<link rel="shortcut icon" href="favicon.ico" />
		<link rel="stylesheet" type="text/css" media="screen" href="public/plugins/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/fonts/style.css">
		<link rel="stylesheet" type="text/css" href="public/css/admin/main.css">
		<link rel="stylesheet" type="text/css" href="public/css/admin/main-responsive.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/iCheck/skins/all.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/fullcalendar/fullcalendar/fullcalendar.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/datepicker/css/datepicker.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/bootstrap-modal/css/bootstrap-modal.css">
		<link rel="stylesheet" type="text/css" href="public/plugins/ckeditor/contents.css">
		<link rel="stylesheet" type="text/css" href="public/css/admin/theme_light.css" id="skin_color">
		<link rel="stylesheet" type="text/css" href="public/css/admin.css">
		<!--[if IE 7]>
		<link rel="stylesheet" type="text/css" href="public/plugins/font-awesome/css/font-awesome-ie7.min.css">
		<![endif]-->

		<!--[if lt IE 9]>
		<script src="public/plugins/respond.min.js"></script>
		<script src="public/plugins/excanvas.min.js"></script>
		<![endif]-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="public/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
		<script src="public/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
		<script src="public/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
		<script src="public/plugins/jquery-maskmoney/jquery.maskMoney.js"></script>
		<script src="public/plugins/jQuery-Tags-Input/jquery.tagsinput.js"></script>
		<script src="public/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="public/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
		<script src="public/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
		<script src="public/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="public/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
		<script src="public/plugins/bootstrap-daterangepicker/moment.min.js"></script>
		<script src="public/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script src="public/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
		<script src="public/plugins/bootstrap-colorpicker/js/commits.js"></script>
		<script src="public/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
		<script src="public/plugins/autosize/jquery.autosize.min.js"></script>
		<script src="public/plugins/select2/select2.min.js"></script>
		<script src="public/plugins/summernote/build/summernote.min.js"></script>
		<script src="public/plugins/ckeditor/ckeditor.js"></script>
		<script src="public/plugins/ckeditor/adapters/jquery.js"></script>
		<script src="public/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="public/plugins/iCheck/jquery.icheck.min.js"></script>
		<script src="public/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
		<script src="public/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
		<script src="public/js/admin/ui-modals.js"></script>
		<script src="public/js/admin/form-elements.js"></script>
		<script src="public/js/admin/main.js"></script>
		<script src="public/js/admin.js"></script>
		<script>

			$( document ).ready( function () {
				Main.init();
				UIModals.init();
				FormElements.init();
			} );

		</script>
		<?php echo $this->headTitle() ?>
	</head>
	<body class="header-default">
		<!-- Header -->
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
						<span class="clip-list-2"></span>
					</button>
					<a class="navbar-brand" href="admin">
						Application Center
					</a>
				</div>
				<div class="navbar-tools">
					<ul class="nav navbar-right">
						<!-- User -->
						<li class="dropdown current-user">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<span class="username"><?php echo $this->adminFullname ?></span>
								<i class="clip-chevron-down"></i>
							</a>
							<ul class="dropdown-menu">
								<li>
									<?php echo $this->link(
										'<i class="clip-exit"></i>&nbsp;Log Out',
										$this->url( array (
											'module' => 'admin',
											'controller' => 'index',
											'action' => 'logout'
										) )
									) ?>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- Main container -->
		<div class="main-container">
			<div class="navbar-content">
				<div class="main-navigation navbar-collapse collapse">
					<div class="navigation-toggler">
						<i class="clip-chevron-left"></i>
						<i class="clip-chevron-right"></i>
					</div>
					<!-- Main menu -->
					<?php echo $this->MainMenu(
						array (
							array (
								'icon' => 'clip-home-3',
								'title' => 'dashboard',
								'url' => array (
									'module' => 'admin'
								),
								'resource' => 'index'
							),
							array (
								'icon' => 'clip-stats',
								'title' => 'statistics',
								'resource' => 'statistics',
								'submenu' => array (
									array (
										'title' => 'apps stats',
										'url' => array (
											'module' => 'admin',
											'controller' => 'statistics',
											'action' => 'plugins',
										),
										'resource' => 'statistics_plugins'
									),
									array (
										'title' => 'installs stats',
										'url' => array (
											'module' => 'admin',
											'controller' => 'statistics',
											'action' => 'installs',
										),
										'resource' => 'statistics_install'
									),
									array (
										'title' => 'webhooks stats',
										'url' => array (
											'module' => 'admin',
											'controller' => 'statistics',
											'action' => 'webhooks',
										),
										'resource' => 'statistics_webhooks'
									),
									array (
										'title' => 'emails stats',
										'url' => array (
											'module' => 'admin',
											'controller' => 'statistics',
											'action' => 'emails',
										),
										'resource' => 'statistics_emails'
									)
								)
							),
							array (
								'icon' => 'clip-users',
								'title' => 'users',
								'resource' => 'users',
								'submenu' => array (
									array (
										'title' => 'access levels',
										'url' => array (
											'module' => 'admin',
											'controller' => 'levels',
											'action' => 'index',
										),
										'resource' => 'levels',
									),
									array (
										'title' => 'admins',
										'url' => array (
											'module' => 'admin',
											'controller' => 'admins',
											'action' => 'index',
										),
										'resource' => 'admins',
									),
									array (
										'title' => 'members',
										'url' => array (
											'module' => 'admin',
											'controller' => 'users',
											'action' => 'index'
										)
									)
								)
							),
							array (
								'icon' => 'fa fa-dollar',
								'title' => 'payments',
								'resource' => 'payments',
								'submenu' => array (
									array (
										'title' => 'transactions',
										'url' => array (
											'module' => 'admin',
											'controller' => 'statistics',
											'action' => 'transactions',
										),
										'resource' => 'statistics_transactions'
									),
									array (
										'title' => 'charges',
										'url' => array (
											'module' => 'admin',
											'controller' => 'statistics',
											'action' => 'charges',
										),
										'resource' => 'statistics_charges'
									),
									array (
										'title' => 'tariff plans',
										'url' => array (
											'module' => 'admin',
											'controller' => 'tariff-plans',
											'action' => 'index',
										),
										'resource' => 'tariff-plans'
									),
									array (
										'title' => 'plans options',
										'url' => array (
											'module' => 'admin',
											'controller' => 'tariff-plan-options',
											'action' => 'index',
										),
										'resource' => 'tariff-plan-options'
									)
								)
							),
							array (
								'icon' => 'fa fa-envelope-o',
								'title' => 'emails',
								'resource' => 'emails',
								'submenu' => array (
									array (
										'title' => 'email templates',
										'url' => array (
											'module' => 'admin',
											'controller' => 'email-templates',
											'action' => 'index',
										),
										'resource' => 'email-templates'
									),
									array (
										'title' => 'list of emails',
										'url' => array (
											'module' => 'admin',
											'controller' => 'emails',
											'action' => 'index',
										),
										'resource' => 'emails_index'
									),
									array (
										'title' => 'mailchimp',
										'url' => array (
											'module' => 'admin',
											'controller' => 'users',
											'action' => 'mailchimp',
										),
										'resource' => 'users_mailchimp'
									)
								)
							),
							array (
								'icon' => 'clip-download',
								'title' => 'webhooks',
								'resource' => 'webhooks',
								'submenu' => array (
									array (
										'title' => 'external webhooks',
										'url' => array (
											'module' => 'admin',
											'controller' => 'webhooks',
											'action' => 'index',
										),
										'resource' => 'webhooks_index',
									),
									array (
										'title' => 'internal webhooks',
										'url' => array (
											'module' => 'admin',
											'controller' => 'webhooks-out',
											'action' => 'index',
										),
										'resource' => 'webhooks-out_index',
									),
								)
							),
							array (
								'icon' => 'clip-clock',
								'title' => 'cron tasks',
								'url' => array (
									'module' => 'admin',
									'controller' => 'cron',
								),
								'resource' => 'cron'
							),
							array (
								'icon' => 'clip-cog-2',
								'title' => 'settings',
								'resource' => 'settings',
								'submenu' => array (
									array (
										'title' => 'general settings',
										'url' => array (
											'module' => 'admin',
											'controller' => 'settings',
											'action' => 'general',
										),
										'resource' => 'settings_general',
									),
									array (
										'title' => 'email settings',
										'url' => array (
											'module' => 'admin',
											'controller' => 'settings',
											'action' => 'email',
										),
										'resource' => 'settings_email',
									)
								)
							),
						)
					) ?>
				</div>
			</div>
			<!-- Main content -->
			<div class="main-content">
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<!-- Breadcrumb -->
							<ol class="breadcrumb">
								<li>
									<i class="clip-home-3"></i>
									<a href="admin">
										<?php echo $this->translate( 'home' ) ?>
									</a>
								</li>
							</ol>
							<!-- Title -->
							<div class="page-header">
								<h1><?php echo $this->title ?></h1>
							</div>
						</div>
					</div>
					<!-- Content -->
					<?php echo $this->layout()->content ?>
				</div>
			</div>
		</div>
		<!-- Footer -->
		<div class="footer clearfix">
			<div class="footer-inner">
				<?php echo $this->translate( 'copyright', date( 'Y' ) ) ?>
			</div>
			<div class="footer-items">
				<span class="go-top"><i class="clip-chevron-up"></i></span>
			</div>
		</div>
		<!-- Event management -->
		<div id="event-management" class="modal fade" tabindex="-1" data-width="760" style="display: none;">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
							&times;
						</button>
						<h4 class="modal-title">Event Management</h4>
					</div>
					<div class="modal-body"></div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-light-grey">
							Close
						</button>
						<button type="button" class="btn btn-danger remove-event no-display">
							<i class='fa fa-trash-o'></i> Delete Event
						</button>
						<button type='submit' class='btn btn-success save-event'>
							<i class='fa fa-check'></i> Save
						</button>
					</div>
				</div>
			</div>
		</div>
		<!-- Dialog box ( modal ) -->
		<div id="dialog-box" class="modal fade" tabindex="-1" data-width="560" style="display: none;">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="modal-title">
					<?php echo $this->translate( 'dialog box' ) ?>
				</h4>
			</div>
			<div class="modal-body">
				<div class="row" id="modal-content"></div>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-light-grey">
					<?php echo $this->translate( 'close' ) ?>
				</button>
				<button type="button" class="btn btn-blue" id="modal-save">
					<?php echo $this->translate( 'save' ) ?>
				</button>
			</div>
		</div>
	</body>
</html>