<div class="admin-side">
	<div class="admins">
		<?php if ( $this->isSuperAdmin ) : ?>
			<p><a href="#" class="btn btn-primary" id="create-new-admin">
					<i class="fa fa-plus"></i>
					<?php echo $this->translate( 'add new admin' ) ?>
				</a></p>
		<?php endif ?>
		<?php if ( count( $this->admins ) ) : ?>
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-external-link-square"></i>
					<?php echo $this->translate( 'admins' ) ?>
				</div>
				<div class="panel-body">
					<div class="row">
						<?php echo $this->formFilter ?>
					</div>
					<table class="table table-hover" id="admins">
						<thead>
						<tr>
							<th><?php echo $this->translate( 'Admin_login' ) ?></th>
							<th><?php echo $this->translate( 'Email' ) ?></th>
							<th><?php echo $this->translate( 'Full name' ) ?></th>
							<th><?php echo $this->translate( 'Access level' ) ?></th>
							<th><?php echo $this->translate( 'Actions' ) ?></th>
						</tr>
						</thead>
						<tbody>
						<?php foreach ( $this->admins as $admin ) : ?>
							<tr>
								<td class="tpl-login"><?php echo $admin['nickname'] ?></td>
								<td class="tpl-email"><?php echo $admin['email'] ?></td>
								<td class="tpl-fullname"><?php echo $admin['fullname'] ?></td>
								<td class="tpl-level"><?php echo $admin['level_name'] ?></td>
								<td class="actions">
									<?php if ( $admin['id'] == $this->viewer->id || $this->isSuperAdmin  ) : ?>
										<?php echo $this->link(
											'<i class="fa fa-edit"></i>',
											$admin['id'],
											array (
												'class' => 'edit btn-sm btn-teal tooltips',
												'data-placement' => 'top',
												'data-original-title' => $this->translate( 'edit' )
											)
										) ?>
									<?php endif ?>
									<?php if ( $this->isSuperAdmin && $admin['access_level'] != 0  ) : ?>
										<?php echo $this->link(
											'<i class="fa fa-times fa fa-white"></i>',
											$admin['id'],
											array (
												'class' => 'delete btn-sm btn-bricky tooltips',
												'data-placement' => 'top',
												'data-original-title' => $this->translate( 'delete' )
											)
										) ?>
									<?php endif ?>
								</td>
							</tr>
						<?php endforeach ?>
						</tbody>
					</table>
				</div>
			</div>
		<?php else : ?>
			<div class="alert alert-info">
				<i class="fa fa-info-circle"></i>
				<?php echo $this->translate( 'no admins' ) ?>
			</div>
		<?php endif ?>
	</div>
</div>
<script type="text/javascript">
	/**
	 * Create new user url.
	 * @var string
	 */
	Admin.createUrl = '<?php echo $this->url( array (
		'action' => 'create'
	) ) ?>';

	/**
	 * Edit user url.
	 * @var string
	 */
	Admin.editUrl = '<?php echo $this->url( array (
		'action' => 'edit'
	) ) ?>';

	/**
	 * Delete user url.
	 * @var string
	 */
	Admin.deleteUrl = '<?php echo $this->url( array (
		'action' => 'delete'
	) ) ?>';

	/**
	 * Calls a dialog-box having set styles beforehand.
	 */
	Admin.setFormExtendedEvents = function ()
	{
		$('#dialog-box label.col-sm-4').each( function ( index, element ) {
			$( element ).removeClass( 'col-sm-4' );
			$( element ).addClass( 'col-sm-3' );
		} );
		$('#dialog-box').modal();
	};

	/**
	 * DOM ready event.
	 */
	$( document ).ready( function ()
	{
		//search by access level
		$('#level').change(
			{ tableId: 'admins', cellId: 'tpl-level' },
			//todo add full list
			Admin.standardSelectorEvent
		);

		$('#create-new-admin').click( Admin.standardCreateAction );
		$('a.edit').click( Admin.standardEditAction );
		$('a.delete').click( Admin.standardDeleteAction );
	} );

</script>