<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<title>Informational notification</title>
	<!--general stylesheet-->
	<style type="text/css">p { padding: 0; margin: 0; }
			h1, h2, h3, p, li { font-family: Helvetica Neue, Helvetica, Arial, sans-serif; }
			td { vertical-align:top;}
			ul, ol { margin: 0; padding: 0;}
			.heading {
				border-radius: 3px;
				-webkit-border-radius: 3px;
				-moz-border-radius: 3px;
				-khtml-border-radius: 3px;
				-icab-border-radius: 3px;
			}
	</style>
</head>
<body background="" bgcolor="#ffffff" leftmargin="0" marginheight="0" marginwidth="0" style="margin: 0px; background-color: #ffffff;" topmargin="0">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody>
		<tr valign="top">
			<td>
			<table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="750">
				<tbody>
					<tr>
						<td bgcolor="#ebebeb" height="30" style="vertical-align: middle; border-bottom-color: #d6d6d6; border-bottom-width: 1px; border-bottom-style: solid;" valign="middle">
						<p style="font-size: 11px; font-weight: bold; color: #8a8a8a; text-align: center;">This is a courtesy notification from <a href="http://spur-i-t.com" style="color: #fd2323;" target="_blank">SpurIT</a></p>
						</td>
					</tr>
					<tr>
						<td align="center" bgcolor="#ffffff" valign="top">
						<table border="0" cellpadding="0" cellspacing="0" width="700">
							<tbody>
								<tr>
									<td height="37" style="height: 37px;" valign="top">&nbsp;</td>
								</tr>
								<tr>
									<td valign="top" width="100%">
									<table border="0" cellpadding="0" cellspacing="0" width="100%">
										<tbody>
											<tr>
												<td height="37" style="height: 37px; border-bottom-color: #d6d6d6; border-bottom-width: 1px; border-bottom-style: solid; vertical-align: middle;" valign="middle">
												<h2 style="margin: 0; padding: 0; font-size: 13px; font-weight: bold; color: #fd2323; text-align: left;">Dear :username,</h2>
												</td>
											</tr>
											<tr>
												<td valign="top">
												<p style="margin: 0; margin-top: 7px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">This is a courtesy notification to let you know that for the previous period of the usage of the <b><a href=":link_to_app_login" target="_blank">:application_name</a></b> application you have exceeded the limit determined for your <b>:client_tariff_plan</b> tariff plan in the <b>:application_name</b> application and haven&#39;t paid for excess of the limit on time. That&#39;s why the work of the application was stopped.</p>

												<p style="margin: 0; margin-top: 17px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">For your <b>:client_tariff_plan</b> tariff plan the following limits exist:</p>

												<p style="margin: 0; margin-top: 17px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">:tariff_plan_options</p>
												&nbsp;

												<p style="margin: 0; margin-top: 17px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">Your statistics for the usage of application for the previous period are the following:</p>

												<p style="margin: 0; margin-top: 17px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">:tariff_plan_stats</p>

												<p style="margin: 0; margin-top: 7px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">The red color in the statistics shows values that exceed the limits established for this tariff plan.</p>
												&nbsp;

												<p style="margin: 0; margin-top: 17px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">If you want to resume the work of the :application_name application you should log-in to your application account using <a href=":link_to_app_login" target="_blank">:link_to_app_login</a> link and make the payment for exceeding the limits of your tariff plan. When we receive the payment, the application will resume its work.</p>

												<p style="margin: 0; margin-top: 7px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;"><b><i>Suggestion:</i></b> to avoid extra costs in future you can change your tariff plan to the plan with a higher price, but where limits have a higher value (if the application has other tariff plans).</p>

												<p style="margin: 0; margin-top: 17px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">If you have any comments or wishes concerning features of our applications, feel free to send it to our e-mail address: <a href="mailto::contact_email">:contact_email</a>. We can be more efficient together!</p>

												<p style="margin: 0; margin-top: 17px; margin-bottom: 10px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">We wish good luck to you and your business!</p>
												</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
								<tr>
									<td height="55" style="height: 55px; vertical-align: middle; border-top-color: #d6d6d6; border-top-width: 1px; border-top-style: solid;" valign="middle">
									<p style="font-size: 11px; font-weight: bold; color: #8a8a8a; text-align: center;">&nbsp;</p>

									<h3 style="margin: 0; padding: 0; font-size: 13px; font-weight: bold; text-align: left;">Best regards,<br />
									<b><a href="http://spur-i-t.com" target="_blank">SpurIT</a></b> team</h3>

									<p>&nbsp;</p>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>
</body>
</html>
