<div class="<?php echo $this->platform ?>">
	<div class="auth clearfix">
		<h1><?php echo $this->translate( $this->platform . ' auth', $this->plugin->name ) ?></h1>
		<div class="container clearfix">
			<?php echo $this->plugin->description ?>
		</div>
		<div class="container clearfix">
			<div class="g_12 no-tb-border" style="text-align:justify">
				<?php echo $this->translate( 'bc auth index page description' ) ?>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>