<form id="payment-form" class="clearfix" action="https://www.2checkout.com/checkout/purchase" method="post">
	<!-- input type="hidden" name="demo" value="Y" / -->
	<input type="hidden" name="sid" value="<?php echo Zend_Controller_Action_HelperBroker::getStaticHelper( '2co' )->getAccountId() ?>" />
	<input type="hidden" name="mode" value="2CO" />
	<input type="hidden" name="lang" value="en" />
	<input type="hidden" name="skip_landing" value="1" />

	<input type="hidden" name="platform" value="<?php echo $this->platform ?>" />
	<input type="hidden" name="shop" value="<?php echo $this->shop ?>" />
	<input type="hidden" name="plugin" value="<?php echo $this->plugin ?>" />
	<input type="hidden" name="plan" value="<?php echo $this->currentPlan ?>" />

	<!-- Main product. -->
	<?php if ( !$this->disableMainProduct ) : ?>
		<input type="hidden" name="li_0_type" value="product" />
		<input type="hidden" id="product-id" name="li_0_product_id" value="" />
		<input type="hidden" id="product-name" name="li_0_name" value="" />
		<input type="hidden" id="product-description" name="li_0_description" value="" />
		<input type="hidden" id="product-price" name="li_0_price" value="" />
		<input type="hidden" name="li_0_quantity" value="1" />
		<input type="hidden" name="li_0_tangible" value="N" />
		<!-- recurrence. -->
		<div>
			<input id="recurrent" type="checkbox" /><!--
			--><label for="recurrent"><strong><?php echo $this->translate( 'use recurring payment' ) ?></strong></label>
			<small><?php echo $this->translate( 'recurring payment description' ) ?></small>
			<input type="hidden" id="product-recurrence" name="li_0_recurrence" value="" />
			<input type="hidden" id="product-duration" name="li_0_duration" value="" />
		</div>
	<?php endif ?>

	<!-- Overdrafts. -->
	<?php if ( !empty ( $this->overdrafts ) ) : $this->productNumber = 0; ?>
		<div id="overdrafts">
			<?php if ( !$this->disableMainProduct ) : ?>
				<input id="with-overdrafts" type="checkbox" /><!--
				--><label for="with-overdrafts">
					<strong><?php

						echo $this->translate(
							'pay for overdraft limits',
							$this->overdraftTotalPrice,
							strtolower( $this->translate(
								array ( 'month', 'months', count( $this->overdrafts ) )
							) )
						)

					?></strong>
				</label>
			<?php else : ?>
				<p><?php

					echo $this->translate(
						'pay for overdraft limits',
						$this->overdraftTotalPrice,
						strtolower( $this->translate(
							array ( 'month', 'months', count( $this->overdrafts ) )
						) )
					)

				?></p>
			<?php endif ?>
			<?php

				$disabled = $this->disableMainProduct ? '' : 'disabled="disabled"';
				foreach ( $this->overdrafts as $_period ) :
					++$this->productNumber;

					?>
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_type" value="product" />
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_product_id" value="<?php echo $_period['id'] ?>" />
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_name" value="<?php echo $this->translate( 'payment for overdraft limits' ) ?>" />
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_description" value="<?php echo $this->translate( 'payment for overdraft limits for', date( "M, Y", strtotime( $_period['period'] .'+ 1 day' ) ) ) ?>" />
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_price" value="<?php echo $_period['price'] ?>" />
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_quantity" value="1" />
					<input <?php echo $disabled ?> type="hidden" name="li_<?php echo $this->productNumber ?>_tangible" value="N" />
			<?php endforeach ?>
		</div>
	<?php endif ?>

	<input type="submit" id="btn" class="btn" value="<?php echo $this->translate( 'checkout with 2co' ) ?>" />
</form>